version: '3.8'

# networks:
#   corp:
#     driver: bridge

services:
  server:
    container_name: server
    build:
      context: ./
      cache_from:
        - nx-docker-nest-next
      dockerfile: ./apps/server/Dockerfile
      args:
        NODE_ENV: 'development'
        BUILD_FLAG: ''
    image: server:nx-dev
    ports:
      - 3000:3000
    environment:
      NODE_ENV: 'development'
      PORT: 3000
    # networks:
    #   - corp
    restart: on-failure

  client:
    container_name: client
    build:
      context: ./
      cache_from:
        - nx-docker-nest-next
      dockerfile: ./apps/client/Dockerfile
      args:
        NODE_ENV: 'development'
        BUILD_FLAG: ''
    image: client:nx-dev
    ports:
      - 4200:4200
    environment:
      NODE_ENV: 'development'
      PORT: 4200
    # networks:
    #   - corp
    restart: on-failure
