# version: '3'
# services:
#   nx-client:
#     container_name: nx-client
#     # image: nx-client
#     build: #This specifies the location of our Dockerfile
#       context: .
#     ports:
#       - '3000:3000'

version: '3.1'

services:
  nx_client:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: nx_client
    volumes:
      - ./dist/apps/client:/usr/src/app
    # networks:
    #   my-network:
    #     aliases:
    #       - nx-client-app
    expose:
      - 3000
    ports:
      - '3000:3000'
    stdin_open: true
